import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import { Navbar } from "@/components/common/navbar";
import { Providers } from "@/components/common/providers";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <Providers>
        <body
          className={cn(
            'min-h-screen font-sans antialiased grainy',
            inter.className
          )}
        >
          {/* Navbar */}
          <Navbar />

          {/* Main Content */}
          {children}

          {/* Toaster */}
          <Toaster position="top-right" expand={true} richColors />
        </body>
      </Providers>
    </html>
  );
}
